version: "3.3"
services:
  openvas:
    ports:
      - "39392:9392"
      - "39390:9390"
      - "32222:22"
    environment:
      - "PASSWORD=123456Qq"
    volumes:
      - "openvas:/data"
    container_name: openvas
    image: openvas
volumes:
  openvas:
