version: "3.3"
services:
  openvas:
    ports:
      - "9392:9392"
      - "9390:9390"
      - "2222:22"
    environment:
      - "PASSWORD=123456Qq"
    volumes:
      - "openvas:/data"
    container_name: openvas
    image: immauss/openvas
volumes:
  openvas:
